### ISSUE TITLE
Is it possible to provide demos of real images?

### ISSUE THREAD

**Issue by MMagicLoren** [guynir42/pyradon#13]
Hi Guy Nir,
Thanks so much for your contribution! I'm really excited to try out pyradon. The README file has some great tips for using the tool, but I'm still having a little trouble with testing with real images. Would you be able to provide a demo file of a real image application like the simulation demo file? I'd love to see it in action! Looking forward to your reply, thanks again!

**Comment by guynir42** [comment]
Hi @MMagicLoren I'm sorry I didn't see your issue until recently. I added another notebook that downloads an example PTF image and runs streak detection on it. 
Please let me know if you have any questions or problems with the code!

**Comment by guynir42** [comment]
Addressed by #15
